### ISSUE TITLE
pre-commit hook fails due to eslint and sample app configs

### ISSUE THREAD

**Issue by TremayneChrist** [Refinitiv/refinitiv-ui#181]
## Context

Cloning the repo and then committing changes will fail due to dependencies not being installed in all of the sample apps.

## Expected Behavior

Clongin the repo and installing npm dependencies on the root should be sufficient enough to commit changes back into the repoository.

## Current Behavior
Commit hook fails to perform linting due to extended configs not being available in the sample apps until their dependencies are installed.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone repo
2. `npm i`
3. Modify a file
4. Stage
5. Commit

**Comment by Sarin-Udompanish** [comment]
Should be fixed with this pull request https://github.com/Refinitiv/refinitiv-ui/pull/160
