### ISSUE TITLE
your [Element Framework (EF) ] documentation in vue section wrote the wrong paths 

### ISSUE THREAD

**Issue by six-face** [Refinitiv/refinitiv-ui#38]
![image](https://user-images.githubusercontent.com/30429241/137475448-803bbe47-fe01-4a15-b72b-8ba890766a0f.png)

according to your building environment, should be:

![image](https://user-images.githubusercontent.com/30429241/137475557-f3d8b053-a04c-4c46-b876-a9cb727f412d.png)

otherwise you will get these errors:

![image](https://user-images.githubusercontent.com/30429241/137475690-316a5f53-beea-46de-8575-33caa5dafc22.png)

and, you are welcome! : )

**Comment by bualoy-napat** [comment]
@six-face  Thank you for raise this issue, we fix it as soon as possible. :D

**Comment by goremikins** [comment]
Updated documentation has been deployed: https://ui.refinitiv.com/book/en/framework-integration/vue.html
