### ISSUE TITLE
[tab-bar] It is not possible to activate a tab using a keyboard

### ISSUE THREAD

**Issue by shlangus** [Refinitiv/refinitiv-ui#395]
## Context

* Versions of browsers: Chrome 103
* OS: Windows 10
* Versions of Element Framework: 6.0.1

## Expected Behavior

It should be possible to activate a tab in `ef-tab-bar` by pressing Enter or Space on a keyboard.

## Current Behavior

It is not possible to activate a tab in `ef-tab-bar` with a keyboard.

## Steps to Reproduce

1. Open the first example at https://ui.refinitiv.com/elements/tab-bar (sorry, but I did not find how to make a permalink to the examples)
2. Focus the tab-bar by clicking on it or by using Tab key on a keyboard. 
3. Select any tab that is not currently active using arrows on a keyboard.
4. Press Enter/Space  

![chrome_t3eAce2a8E](https://user-images.githubusercontent.com/6114091/178481971-72ebaaf5-48d8-4aaf-85b9-2aab3afbbe42.gif)

**Comment by Sarin-Udompanish** [comment]
Hi @shlangus, Thank you for raising the issue. As I mentioned in https://github.com/Refinitiv/refinitiv-ui/issues/396.
A tab is already active when pressing an arrow key but `value-changed` event is not fired so the demo show incorrect title.
We will fix it as soon as possible.
