### ISSUE TITLE
[tab-bar] An active tab loses its active state when another tab is selected using a keyboard

### ISSUE THREAD

**Issue by shlangus** [Refinitiv/refinitiv-ui#396]
## Context

* Versions of browsers Chrome 103
* OS: Windows 10
* Versions of Element Framework: 6.0.1

## Expected Behavior

A tab in a tab bar should remain active when a user navigates across tabs using a keyboard

## Current Behavior

A tab in a tab bar loses its active state when a user navigates across tabs using a keyboard

## Steps to Reproduce

1. Open the first example at https://ui.refinitiv.com/elements/tab-bar (sorry, but I did not find how to make a permalink to the examples)
2. Click the first tab to ensure it is active
3. Move the cursor out of tab-bar
4. Move to another tab by pressing the right arrow on a keyboard
5. Notice that the first tab is not highlighted as active and a click on it produces a `value-changed` event.
![chrome_KekybPzPZT](https://user-images.githubusercontent.com/6114091/178486719-3360b367-2292-406b-b207-7df53d38d1f5.gif)

**Comment by Sarin-Udompanish** [comment]
Hi @shlangus, Thank you for raising the issue. It is expected behavior. Pressing an arrow key will moves focus to the next tab and activates the newly focused tab but we just found that it doesn't fired `value-changed` event when pressing an arrow key so the demo show incorrect title. We will fix it as soon as possible.

**Comment by shlangus** [comment]
Hello @Sarin-Udompanish and thank you for your reply. 
We were going to use this component for a heavy asynchronous in-app navigation that also can be cancelled but now I see that this is not a use case for this component :)
