### ISSUE TITLE
[text-field]: there is no type def for `detail` from `value-change` event

### ISSUE THREAD

**Issue by zapkub** [Refinitiv/refinitiv-ui#399]
## Context

Microsoft Edge
Version 103.0.1264.49 (Official build) (64-bit)

Windows 11

`@refinitiv-ui/elements@6.0.1`

## Expected Behavior

`detail` attribute should also appear in `Event` from `value-changed` event in type definition

## Current Behavior
no `detail` attribute in typescript lead to compile error or need to skip type checking or explicit type casting with `CustomEvent<TextField>`
![image](https://user-images.githubusercontent.com/4373581/179134791-0895000d-ab0d-4c10-b001-d1154de1bd7d.png)

## Steps to Reproduce
1. follow the React sample and use `text-field` attribute with Typescript React
2. handle `value-changed` event with event listener
3. observe callback argument event

**Comment by wsuwt** [comment]
You can access generic event types from the package's root i.e.,

`import { ValueChangedEvent } from '@refinitiv-ui/elements';`

**Comment by zapkub** [comment]
Thanks!
